apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-deployment
  labels:
    app: configurationservice
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
       maxUnavailable: 1
       maxSurge: 1
  template:
    metadata:
      labels:
        app: configurationservice
    spec:
      containers:
        - name: configurationservice
          image: 212487160593.dkr.ecr.ap-south-1.amazonaws.com/configuration-service:build
          imagePullPolicy: Always
          ports:
              - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
                #  envFrom: 
                #  - configMapRef:
              #  name: cs-cm
